# Generated by Django 5.1 on 2024-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='a', max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
