# Generated by Django 5.1 on 2024-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='a', max_length=1200),
        ),  preserve_default=False,
    
    migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(max_length=600),
        ),
    ]
    
