# Generated by Django 5.1 on 2024-09-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_conteudo_post_foto_post_subtitulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='foto',
            new_name='imagem',
        ),
    ]